namespace TMK.Utils.Interfaces.Base
{
    public interface IAutogenerated
    {
        /// <summary>
        /// Запись генерирована автоматически
        /// </summary>
        bool IsAutogenerated { get; set; }
    }
}
