version: "3.4"

services:
    api:
        image: lazar_api
        build:
          context: .
          dockerfile: Dockerfile
        container_name: lazar_api
        ports:
          - "8080:80"
        depends_on:
          - db

    db:
        image: "mcr.microsoft.com/mssql/server:2022-latest"
        container_name: sql_server2022
        ports: # not actually needed, because the two services are on the same network
            - "127.0.0.1:1433:1433" 
        environment:
            - ACCEPT_EULA=y
            - SA_PASSWORD=A&VeryComplex123Password